[detection]
widen_radius = 15 # a value I think works....
tag_width = 2 # cm
camera_distance = 58 # cm, YOU HAVE TO CHANGE THIS TO REALITY!!!

[arena]
ring_r = 55 # in cm
nleds = 198
baudrate = 115200 # set by what the arduino expects

