# spaces and indentations do not matter

[[setups]]
    label  "One stationary sun" # this label will be on the button that evokes this setup, and therefore is limited to 60 characters
    [[setups.suns]]
        link_factor = 0 # the order of `link_factor`, `width`, `red`, `green`, and `blue` does not matter
        green = 255 # `red` and `blue` are assumed to be 0 here
        # this sun's `width` is assumed to be 1


