# spaces and indentations do not matter

[[setups]]
    label = "One stationary green sun" # this label will be on the button that evokes this setup, and therefore is limited to 60 characters
    [[setups.suns]]
        link_factor = 0 # the order of `link_factor`, `width`, `red`, `green`, and `blue` does not matter
        green = 255 # `red` and `blue` are assumed to be 0 here
        # this sun's `width` is assumed to be 1

[[setups]] # you can only have 26 setups, because there are only 26 letters and therefore keys on a English keyboard
    label = "Two different suns"
    [[setups.suns]] # you can have as many suns as you like
        link_factor = 1.5
        azimuth = 90
        width = 11
        green = 255
        red = 100
    [[setups.suns]]
        link_factor = -0.8
        azimuth = 180
        width = 3
        blue = 255
        red = 41
        green = 128

[[setups]]
    label = "Three stationary suns"
    [[setups.suns]] # you can have as many suns as you like
        link_factor = 0
        azimuth = 0
        width = 1
        red = 255
    [[setups.suns]] # you can have as many suns as you like
        link_factor = 0
        azimuth = 90
        width = 1
        green = 255
    [[setups.suns]]
        link_factor = 0
        azimuth = 180
        width = 1
        blue = 255

[[setups]]
    label = "Crazy"
    [[setups.suns]]
        link_factor = 2
        green = 255
    [[setups.suns]]
        azimuth = 50
        link_factor = 1
        blue = 255
    [[setups.suns]]
        azimuth = 100
        link_factor = 0
        red = 255
    [[setups.suns]]
        azimuth = 150
        link_factor = -1
        green = 255
        red = 255
    [[setups.suns]]
        azimuth = 200
        link_factor = -2
        blue = 255
        red = 255
    [[setups.suns]]
        azimuth = 250
        link_factor = 0.5
        blue = 255
        green = 255
    [[setups.suns]]
        azimuth = 300
        link_factor = -0.5
        red = 255
        blue = 255
        green = 255
