# Each setup should have a label and at least 1 sun. The label cannot be `Off` (that is reserved as an off-button). Each sun should have a link_factor (a number that ranges from minus infinity to plus infinity; typically -1 -- 1) and at least one color intensity (an integer between 0 and 255, typically green = 255). Each sun can have width (an odd integer between 1 and the number of LEDs in the strip: 198, and defaults to 1), and color intensities (defaults to 0). Each setup can also have a camera (specifying what camera you want to use). The camera can only be one of 480, 1232, 1080, or 2464 (this specifies the size of the frame used, but has implications about the resolution and speed of the camera), and defults to 1080.
# 
# See the [`settings.toml` file](settings.toml) for example.

# spaces and indentations do not matter

[[setups]]
    label = "One stationary sun" # this label will be on the button that evokes this setup, and therefore is limited to 60 characters
    [[setups.suns]]
        link_factor = 0 # the order of `link_factor`, `width`, `red`, `green`, and `blue` does not matter
        green = 255 # `red` and `blue` are assumed to be 0 here
        # this sun's `width` is assumed to be 1

[[setups]] # you can only have 26 setups, because there are only 26 letters and therefore keys on a English keyboard
    label = "Two different suns"
    [[setups.suns]] # you can have as many suns as you like
        link_factor = 1.5
        azimuth = 90
        width = 11
        green = 255
        red = 100
    [[setups.suns]]
        link_factor = -0.8
        azimuth = 180
        width = 3
        blue = 255
        red = 41
        green = 128

[[setups]]
    label = "Three stationary suns"
    [[setups.suns]] # you can have as many suns as you like
        link_factor = 0
        azimuth = 0
        width = 1
        red = 255
    [[setups.suns]] # you can have as many suns as you like
        link_factor = 0
        azimuth = 90
        width = 1
        green = 255
    [[setups.suns]]
        link_factor = 0
        azimuth = 180
        width = 1
        blue = 255

[[setups]]
    label = "Crazy"
    [[setups.suns]]
        width = 11
        link_factor = 2
        green = 255
    [[setups.suns]]
        azimuth = 50
        link_factor = 1
        blue = 255
    [[setups.suns]]
        azimuth = 100
        link_factor = 0
        red = 255
    [[setups.suns]]
        azimuth = 150
        link_factor = -1
        green = 255
        red = 255
    [[setups.suns]]
        azimuth = 200
        link_factor = -2
        blue = 255
        red = 255
    [[setups.suns]]
        azimuth = 250
        link_factor = 0.5
        blue = 255
        green = 255
    [[setups.suns]]
        azimuth = 300
        link_factor = -0.5
        red = 255
        blue = 255
        green = 255

[[setups]]
    label = "Three moving suns"
    [[setups.suns]] # you can have as many suns as you like
        link_factor = 4
        azimuth = 0
        width = 1
        red = 255
    [[setups.suns]] # you can have as many suns as you like
        link_factor = 2
        azimuth = 90
        width = 1
        green = 255
    [[setups.suns]]
        link_factor = -2
        azimuth = 180
        width = 1
        blue = 255

[[setups]]
    label = "Camera width 480"
    camera = 480
    [[setups.suns]]
        link_factor = 1
        green = 255

[[setups]]
    label = "Camera width 1232"
    camera = 1232
    [[setups.suns]]
        link_factor = 1
        green = 255

[[setups]]
    label = "Camera width 1080"
    camera = 1080
    [[setups.suns]]
        link_factor = 1
        green = 255

[[setups]]
    label = "Camera width 2464"
    camera = 2464
    [[setups.suns]]
        link_factor = 1
        green = 255
