[camera]
width=480
height=640

[client]
fps = 10

[detection]
tag_pixel_width = 200
widen_radius = 15


[arena]
nleds = 100
ring_r = 350.3 # in cm
origo_offset = [240, 320] # in pixels
cm_per_pixel = 2.2
