# Raspberry Pi First Boot Setup
[system]
hostname = "rpihost"

[user]
name = "yakir"
password = "raspberry"
password_encrypted = false

[ssh]
enabled = true
authorized_keys = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvWDWmVSoNauNSy/H2PWYQ729tfD2o3RL6D/9ZdZ4O0J/UJshx/frseqFwjiVJTEisojMVL+Il+o14Tr1p3fyMJu/3YA/+bxRK4S0sW2OUeDOyn82P+Byg9RtuFuO57HrDUaInCqKmqtzgAAZiiCFYBNcB11yT1qd0p5BWqQpE6uMWPXu6gRYjR94NMNmveOATwdbqQkhd1fpxagCGC6NuMCc6OiJjCtHPmGw4hhlQvBL0bdBewardWtvomuqnH9ZBwnoqVtc4lvfMZIL7BG3h1P+UdD8XhIi4ixf5H8ShHWt2vRTSyxKjjLHC3mkAJPEHEr8HZtfOQGwlgvCKmf5L yakir@qbi-lat" ]
# this seems to broken in RPi's "init_config" and it sets "-k" instead of "-p"
# password_authentication = true

[wlan]
country = "se"
ssid = "Ermahgerds"
password = "is it though, isn't it just Steven"
password_encrypted = false
hidden = false

[locale]
keymap = "us"
timezone = "Europe/Stockholm"

